# Generated by Django 4.1.7 on 2023-02-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_abstract_blog_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hero_image',
            field=models.URLField(),
        ),
    ]
