# Generated by Django 4.1.7 on 2023-02-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_hero_image_alt_alter_blog_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='cat_1',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cat_2',
        ),
    ]
